### ISSUE TITLE
macOS 14 support? 

### ISSUE THREAD

**Issue by ahaghgoo** [ewlcheng/launchbar-actions#2]
I may be quick with this, but the LaunchBar action is giving me errors since upgrading to Sonoma.  I'm wondering if this is a security enabling issue since it's not working on any application.  

I also don't know how to locate the specific error in the Console logs as searching for Menubar Search or LaunchBar didn't fetch any results in the Console.app.  

Thanks for the consideration!  

![Screenshot 2023-10-17 at 11 54 22](https://github.com/ewlcheng/launchbar-actions/assets/1308002/3d75e5fd-c1e0-456e-bfa4-68e798bac4d3)

**Comment by ewlcheng** [comment]
Hi, unfortunately without more information, I do not know what the issue is. I also have Sonoma installed and it does work for me, so that doesn't seem to be the issue.

The script isn't really doing anything miraculous, it is just running an apple script and then parsing the results in js. Perhaps you can first try running this apple script in script editor to see if it is returning a result.

```
tell application "System Events" to tell (process 1 where frontmost is true)
	tell menu bar 1
		return entire contents of menu bar items
	end tell
end tell
```

**Comment by ahaghgoo** [comment]
Hi Edward, it currently works.  Not sure what happened, but it's working now.  Sorry for the trouble.
